<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRznkp1w\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRznkp1w/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRznkp1w.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRznkp1w\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRznkp1w\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Rznkp1w',
    'container.build_id' => '5acde367',
    'container.build_time' => 1527173005,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRznkp1w');
