<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6hdxe97\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6hdxe97/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container6hdxe97.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container6hdxe97\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container6hdxe97\appDevDebugProjectContainer(array(
    'container.build_hash' => '6hdxe97',
    'container.build_id' => 'dbf58873',
    'container.build_time' => 1527002831,
), __DIR__.\DIRECTORY_SEPARATOR.'Container6hdxe97');
